/**/teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 4
    scale_linear:
      x: 1.0

    axis_angular:
      yaw: 0
    scale_angular:
      yaw: -0.3

    enable_button: 6  # L2 shoulder button

/**/joy_node:
  ros__parameters:
    deadzone: 0.3
    autorepeat_rate: 20.0

/**/cmd_vel_to_ackermann:
  ros__parameters:
    linear_min: 0.5